version: '3'

services:

  app:
    build: .
    ports:
    - "8000:8000"

  db:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: managers
    ports:
      - "5432:5432"
